default_stages: [commit]
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
      - id: pretty-format-json
        args:
        - '--autofix'
        - '--no-sort-keys'
      - id: check-yaml
        args:
        - '--allow-multiple-documents'
      - id: check-json
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
        - id: terraform_fmt
        - id: terraform_validate
        - id: terraform_tflint
          args:
            - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - id: terraform_checkov
          args:
            - --args=--config-file __GIT_WORKING_DIR__/.checkov.yaml
        - id: terraform_docs
          args:
            - --args=--config=.terraform-docs.yaml
