name: Terraform Plan

on:
  workflow_call:
    inputs:
      gh_environment:
        required: false
        type: string
        default: null
      tf_version:
        required: false
        type: string
        default: 'latest'
      working_directory:
        required: true
        type: string
      plan_file_name:
        required: true
        type: string
      var_file:
        required: false
        type: string
      command_option_args:
        required: false
        type: string
        default: ''

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Initialize Terraform
        run: |
          set -x
          terraform init -input=false
        working-directory: ${{ inputs.working_directory }}

      - name: Terraform Plan
        run: |
          if [ -n "${{ inputs.var_file }}" ]; then
            terraform plan -out=${{ inputs.plan_file_name }} -var-file=${{ inputs.var_file }} ${{ inputs.command_option_args }}
          else
            terraform plan -out=${{ inputs.plan_file_name }} ${{ inputs.command_option_args }}
          fi
        working-directory: ${{ inputs.working_directory }}

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.working_directory }}/${{ inputs.plan_file_name }}
