name: Terraform - Apply

on:
  workflow_call:
    inputs:
      gh_environment:
        required: false
        type: string
        default: null
      tf_version:
        required: false
        type: string
        default: 'latest'
      working_directory:
        required: true
        type: string
      plan_file_name:
        required: true
        type: string
      backend_file:
        required: false
        type: string
      var_file:
        required: false
        type: string

jobs:
  apply:
    name: Apply Terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Set Azure Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          set -x
          if [ -n "${{ inputs.backend_file }}" ]; then
            terraform init -backend-config=${{ inputs.backend_file }}
          else
            terraform init
          fi
        working-directory: ${{ inputs.working_directory }}

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.working_directory }}

      - name: Apply Terraform Plan
        run: terraform apply -input=false -auto-approve ${{ inputs.plan_file_name }}
        working-directory: ${{ inputs.working_directory }}
