name: Terraform - Static Code Analysis

on:
  workflow_call:
    inputs:
      gh_environment:
        required: false
        type: string
        default: null

jobs:
  inspect:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    environment: ${{ inputs.gh_environment }}
    steps:
      - uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: static-analysis
        with:
          tools: 'iacfilescanner, trivy, terrascan, templateanalyzer, checkov'

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.static-analysis.outputs.sarifFile }}

      - name: Upload alerts file as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: alerts
          path: ${{ steps.static-analysis.outputs.sarifFile }}
